#!/usr/bin/perl
# Copyright (c) 2008, 2009 Landry Breuil <landry@openbsd.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use warnings;
use strict;
use OpenBSD::PackageManager::Controller;
use OpenBSD::PackageManager::CursesView;
use OpenBSD::PackageManager::DBIModel;
use Getopt::Long;

my ($m, $c, $v, $graphic);

print "Initializing database...";
$m = OpenBSD::PackageManager::DBIModel->new();
print "done\n";
$c = OpenBSD::PackageManager::Controller->new($m);
$v = OpenBSD::PackageManager::CursesView->new($m) unless defined $v;

$c->{view} = $v;
$v->{ctrl} = $c;
$m->{view} = $v;
$v->start;

1;
